### ISSUE TITLE
Update geh-timeseries infrastructure to use new TF modules and new Subscription

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/the-outlaws#46]
Currently the domains are only configured to deploy to an environment as a Resource Group.

We need to change that in each domain, so the Terraform supports deploying to a subscription instead.
This means adding a data pointer to a subscription, and other small changes to the infrastructure of each domain.

## AC 

- [ ] Uses new TF Modules
- [ ] Can deploy to new subscriptions

**Comment by djorgensendk** [comment]
duplicate #82
